services:
  db:
    image: psql
    container_name: psql
    environment:
      POSTGRES_PASSWORD: leffe
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    restart: unless-stopped

  backend:
    image: tomcat
    container_name: tomcat
    ports:
      - 8443:8443
    networks:
      - my_network
    restart: unless-stopped

  web:
    image: apache
    container_name: apache
    ports:
      - 50000:443
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
